name: acdc_cardiac
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _tflow_select=2.3.0=mkl
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - absl-py=2.3.1=pyhd8ed1ab_0
  - aiodns=3.5.0=py310h06a4308_1
  - aiohappyeyeballs=2.6.1=py310h06a4308_0
  - aiohttp=3.13.2=py310hee96239_0
  - aiosignal=1.4.0=py310h06a4308_0
  - anyio=4.10.0=py310h06a4308_0
  - argon2-cffi=25.1.0=py310h06a4308_0
  - argon2-cffi-bindings=25.1.0=py310hee96239_0
  - asttokens=3.0.0=py310h06a4308_0
  - astunparse=1.6.3=py_0
  - async-lru=2.0.5=py310h06a4308_0
  - async-timeout=5.0.1=py310h06a4308_0
  - attrs=25.4.0=py310h06a4308_2
  - babel=2.17.0=py310h06a4308_0
  - backports.zstd=1.2.0=py310h69bd2ac_0
  - beautifulsoup4=4.14.2=py310h06a4308_0
  - blas=1.0=openblas
  - bleach=6.3.0=py310h06a4308_0
  - blinker=1.9.0=py310h06a4308_1
  - bottleneck=1.4.2=py310haa0f9ac_1
  - brotli=1.2.0=h27d5ac6_0
  - brotli-bin=1.2.0=h1421c7b_0
  - brotli-python=1.2.0=py310h3dd09e2_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2025.12.2=h06a4308_0
  - cached-property=1.5.2=py_0
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=6.2.4=pyhd8ed1ab_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.11.12=py310h06a4308_0
  - cffi=1.17.1=py310h1fdaa30_1
  - charset-normalizer=3.4.4=py310h06a4308_0
  - click=8.3.1=pyh8f84b5b_1
  - comm=0.2.3=py310h06a4308_0
  - contourpy=1.3.2=py310h3788b33_0
  - cryptography=39.0.0=py310h65dfdc0_0
  - cudatoolkit=11.2.2=hc23eb0c_13
  - cudnn=8.1.0.77=h90431f1_0
  - cycler=0.12.1=py310h06a4308_0
  - cyrus-sasl=2.1.28=h9c0eb46_1
  - dbus=1.16.2=h5bd4931_0
  - debugpy=1.8.16=py310hbdd6827_1
  - decorator=5.2.1=py310h06a4308_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - eigen=5.0.1=hf04f85b_0
  - exceptiongroup=1.3.0=py310h06a4308_0
  - executing=2.2.1=py310h06a4308_0
  - expat=2.7.3=h7354ed3_4
  - ffmpeg=4.2.2=h20bf706_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonttools=4.61.1=py310h3406613_0
  - freetype=2.13.3=h4a9f257_0
  - frozenlist=1.7.0=py310h9548a50_0
  - gast=0.4.0=pyhd3eb1b0_0
  - giflib=5.2.2=h5eee18b_0
  - glib=2.84.4=h5bdd934_0
  - glib-tools=2.84.4=h8875d55_0
  - gmp=6.3.0=h6a678d5_0
  - gnutls=3.6.15=he1e5248_0
  - google-auth=2.45.0=pyhd8ed1ab_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - graphite2=1.3.14=h295c915_1
  - grpc-cpp=1.46.1=h33aed49_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h11=0.16.0=py310h06a4308_1
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=4.3.0=hf52aaf7_1
  - hdf5=1.12.1=h70be1eb_2
  - hpack=4.1.0=py310h06a4308_0
  - html5lib=1.1=pyhd3eb1b0_0
  - httpcore=1.0.9=py310h06a4308_0
  - httpx=0.28.1=py310h06a4308_1
  - hyperframe=6.1.0=py310h06a4308_0
  - icu=58.2=he6710b0_3
  - idna=3.11=py310h06a4308_0
  - imageio=2.37.2=py310h7040dfc_0
  - importlib-metadata=8.7.0=py310h06a4308_0
  - importlib_resources=6.5.2=py310h06a4308_0
  - ipykernel=6.31.0=py310h7040dfc_0
  - ipython=8.30.0=py310h06a4308_0
  - ipython_pygments_lexers=1.1.1=py310h06a4308_0
  - ipywidgets=8.1.7=py310h06a4308_0
  - jedi=0.19.2=py310h06a4308_0
  - jinja2=3.1.6=py310h06a4308_0
  - jpeg=9e=h5eee18b_3
  - json5=0.12.1=py310h06a4308_0
  - jsonschema=4.25.0=py310h06a4308_1
  - jsonschema-specifications=2025.9.1=py310h06a4308_0
  - jupyter=1.1.1=py310h06a4308_0
  - jupyter-lsp=2.2.5=py310h06a4308_0
  - jupyter_client=8.6.3=py310h06a4308_1
  - jupyter_console=6.6.3=py310h06a4308_0
  - jupyter_core=5.9.1=py310h06a4308_0
  - jupyter_events=0.12.0=py310h06a4308_1
  - jupyter_server=2.17.0=py310h06a4308_0
  - jupyter_server_terminals=0.5.3=py310h06a4308_0
  - jupyterlab=4.5.0=py310h06a4308_0
  - jupyterlab_pygments=0.3.0=py310h06a4308_0
  - jupyterlab_server=2.28.0=py310h06a4308_0
  - jupyterlab_widgets=3.0.15=py310h06a4308_0
  - keras=2.10.0=py310h06a4308_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py310h24d9097_0
  - krb5=1.20.1=h568e23c_1
  - lame=3.100=h7b6447c_0
  - lazy_loader=0.4=py310h06a4308_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libaec=1.1.4=h3f801dc_0
  - libbrotlicommon=1.2.0=h32cd6e7_0
  - libbrotlidec=1.2.0=ha2c5f68_0
  - libbrotlienc=1.2.0=h2e96acb_0
  - libclang13=14.0.6=default_he11475f_2
  - libcups=2.4.2=ha637b67_0
  - libcurl=7.87.0=h6312ad2_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=h8f2d780_0
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libglib=2.84.4=h77a78f3_0
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libllvm14=14.0.6=hecde1de_4
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libnsl=2.0.0=h5eee18b_0
  - libopenblas=0.3.30=h46f56fc_2
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.53=h421ea60_0
  - libpq=12.15=h37d81fd_1
  - libprotobuf=3.20.3=he621ea3_0
  - libsodium=1.0.20=heac8642_0
  - libsqlite=3.51.1=h0c1763c_1
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtasn1=4.20.0=ha30cf84_0
  - libtiff=4.5.1=hffd6297_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hcbfbd50_0
  - libxslt=1.1.37=h2085143_0
  - libzlib=1.3.1=hb25bd0a_0
  - loguru=0.7.3=py310h06a4308_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown=3.10=pyhcf101f3_1
  - markupsafe=3.0.3=py310h3406613_0
  - matplotlib-inline=0.2.1=py310h06a4308_0
  - mistune=3.1.2=py310h06a4308_0
  - multidict=6.7.0=py310hee96239_0
  - munkres=1.1.4=py_0
  - mysql=5.7.24=he378463_2
  - nbclient=0.10.2=py310h06a4308_0
  - nbconvert=7.16.6=py310h06a4308_0
  - nbconvert-core=7.16.6=py310h06a4308_0
  - nbconvert-pandoc=7.16.6=py310h06a4308_0
  - nbformat=5.10.4=py310h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py310h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.4.2=py310h06a4308_0
  - nibabel=5.3.2=pyha770c72_1
  - notebook=7.5.0=py310h06a4308_0
  - notebook-shim=0.2.4=py310h06a4308_0
  - nspr=4.37=h8459abe_0
  - nss=3.117=h3135ca0_0
  - numexpr=2.14.1=py310ha5a4a6c_0
  - oauthlib=3.3.1=py310h06a4308_0
  - opencv=4.6.0=py310ha16400d_5
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=1.1.1w=h7f8727e_0
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - overrides=7.7.0=py310h06a4308_0
  - packaging=25.0=py310h06a4308_1
  - pandas=2.0.3=py310h1128e8f_0
  - pandoc=3.8=h06a4308_0
  - pandocfilters=1.5.1=py310h06a4308_0
  - parso=0.8.5=py310h06a4308_0
  - pcre2=10.46=hf426167_0
  - pexpect=4.9.0=py310h06a4308_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.5.0=py310h06a4308_0
  - prometheus_client=0.21.1=py310h06a4308_0
  - prompt-toolkit=3.0.52=py310h06a4308_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - propcache=0.3.1=py310h5eee18b_0
  - psutil=7.0.0=py310hee96239_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py310h06a4308_0
  - pyasn1=0.6.1=py310h06a4308_0
  - pyasn1-modules=0.4.2=py310h06a4308_0
  - pycares=4.10.0=py310ha137689_0
  - pycparser=2.22=py310h06a4308_0
  - pygments=2.19.2=py310h06a4308_0
  - pyjwt=2.10.1=py310h06a4308_1
  - pyopenssl=23.2.0=py310h06a4308_0
  - pyparsing=3.3.1=pyhcf101f3_0
  - pyqt=5.15.4=py310hd8f1fbe_0
  - pyqt5-sip=12.9.0=py310hd8f1fbe_0
  - pysocks=1.7.1=py310h06a4308_1
  - python=3.10.13=h7a1cb2a_0
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-fastjsonschema=2.21.2=py310h06a4308_0
  - python-json-logger=4.0.0=py310h06a4308_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.10=3_cp310
  - pytz=2025.2=py310h06a4308_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pyyaml=6.0.3=py310h591646f_0
  - pyzmq=27.1.0=py310hcf8288c_1
  - qt-main=5.15.2=h5b8104b_9
  - qt-webengine=5.15.9=h9ab4d14_7
  - qtconsole=5.7.0=py310h06a4308_0
  - qtpy=2.4.3=py310h06a4308_0
  - qtwebkit=5.212=h3fafdc1_5
  - re2=2022.04.01=h295c915_0
  - readline=8.3=hc2a1206_0
  - referencing=0.37.0=py310h06a4308_0
  - requests=2.32.5=py310h06a4308_1
  - requests-oauthlib=2.0.0=py310h06a4308_0
  - rfc3339-validator=0.1.4=py310h06a4308_0
  - rfc3986-validator=0.1.1=py310h06a4308_0
  - rpds-py=0.28.0=py310h498d7c9_0
  - rsa=4.9.1=pyhd8ed1ab_0
  - seaborn=0.13.2=py310h06a4308_3
  - send2trash=1.8.2=py310h06a4308_1
  - setuptools=80.9.0=py310h06a4308_0
  - sip=6.5.1=py310h295c915_0
  - six=1.17.0=py310h06a4308_0
  - snappy=1.1.10=h6a678d5_1
  - sniffio=1.3.1=py310h06a4308_0
  - soupsieve=2.5=py310h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - stack_data=0.6.3=py310h06a4308_0
  - tensorboard=2.10.1=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.1=py310h52d8a92_0
  - tensorboard-plugin-wit=1.8.1=py310h06a4308_0
  - tensorflow=2.10.0=mkl_py310h24f4fea_0
  - tensorflow-base=2.10.0=mkl_py310hb9daa73_0
  - tensorflow-estimator=2.10.0=py310h06a4308_0
  - termcolor=3.2.0=py310h06a4308_0
  - terminado=0.18.1=py310h06a4308_0
  - tinycss2=1.4.0=py310h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.2.1=py310h06a4308_0
  - tornado=6.5.4=py310h47b2149_0
  - traitlets=5.14.3=py310h06a4308_0
  - typing-extensions=4.15.0=py310h06a4308_0
  - typing_extensions=4.15.0=py310h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=17.0.0=py310h7c4b9e2_1
  - urllib3=2.6.2=pyhd8ed1ab_0
  - uvloop=0.22.1=py310h939ff40_1
  - wcwidth=0.2.13=py310h06a4308_0
  - webencodings=0.5.1=py310h06a4308_1
  - websocket-client=1.8.0=py310h06a4308_0
  - werkzeug=3.1.4=pyhcf101f3_0
  - wheel=0.45.1=py310h06a4308_0
  - widgetsnbextension=4.0.14=py310h06a4308_0
  - wrapt=2.0.1=py310h47b2149_0
  - x264=1!157.20191217=h7b6447c_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.22.0=py310hee96239_0
  - zeromq=4.3.5=hb0a5e54_1
  - zipp=3.23.0=py310h06a4308_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - albumentations==1.3.0
      - efficientnet==1.0.0
      - flatbuffers==25.12.19
      - grpcio==1.76.0
      - h5py==3.15.1
      - image-classifiers==1.0.0
      - joblib==1.5.3
      - keras-applications==1.0.8
      - libclang==18.1.1
      - matplotlib==3.10.8
      - numpy==1.23.5
      - opencv-python-headless==4.6.0.66
      - pillow==12.0.0
      - protobuf==3.19.6
      - pywavelets==1.8.0
      - qudida==0.0.4
      - scikit-image==0.19.3
      - scikit-learn==1.7.2
      - scipy==1.10.1
      - segmentation-models==1.0.1
      - tensorflow-gpu==2.10.1
      - tensorflow-io-gcs-filesystem==0.37.1
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
prefix: /home/charliechen/miniconda3/envs/acdc_cardiac
